version: '3.12'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1s
      timeout: 5s
      retries: 15
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - backend-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    restart: always
#    ports:
#      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
      - chroma
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./fixtures:/app/fixtures:ro

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    restart: always
    ports:
      - "8000:${CHROMADB_PORT}"
    volumes:
      - chroma-data:/chroma/chroma
    env_file:
      - ".env"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=$CHROMADB_PORT
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
volumes:
  backend-data:
  chroma-data:
